### PR TITLE
Added report info API

### PR DESCRIPTION
**Pull request by JSDID**

### CODE REVIEW

**Review by kamabzalov — COMMENTED** [review]
@JSDID на все действия сохранения надо тоже добавить сообщение о сохранении (мне в четверг на это клиент указал)

**Review by kamabzalov — COMMENTED** [review]
@JSDID что не работает? Что надо спросить у бэка?

**Comment by JSDID** [comment]
Этот ендпоинт возвращает нам taskuid. Но при попытке получить данные с /api/v1/reports/{taskuid}/report - у нас ошибка
photo_2024-08-18_20-00-32 (2)
photo_2024-08-18_20-00-32

**Comment by JSDID** [comment]
curl "https://app.admss.com/api/v1/reports/ccf0487f-5059-4924-9469-3be04d58ae89/report" ^
  -H "Accept: application/pdf" ^
  -H "Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6" ^
  -H "Authorization: Bearer 49df9455-d614-439b-8fef-19687e4e80db" ^
  -H "Connection: keep-alive" ^
  -H "Origin: http://localhost:3003" ^
  -H "Referer: http://localhost:3003/" ^
  -H "Sec-Fetch-Dest: empty" ^
  -H "Sec-Fetch-Mode: cors" ^
  -H "Sec-Fetch-Site: cross-site" ^
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" ^
  -H ^"sec-ch-ua: ^\^"Not)A;Brand^\^";v=^\^"99^\^", ^\^"Google Chrome^\^";v=^\^"127^\^", ^\^"Chromium^\^";v=^\^"127^\^"^" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^"

**Comment by JSDID** [comment]
reportinfo вчера все возвращал корректно (с этим есть вчерашние скрины), а сегодня - ошибка.
curl "https://app.admss.com/api/v1/reports/aa8f3fd4-f753-4306-a211-46c043bf5b9c/reportinfo" ^
  -H "Accept: application/json, text/plain, */*" ^
  -H "Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6" ^
  -H "Authorization: Bearer 7cca8947-fff2-4c91-a483-370a548881f2" ^
  -H "Connection: keep-alive" ^
  -H "Origin: http://localhost:3003" ^
  -H "Referer: http://localhost:3003/" ^
  -H "Sec-Fetch-Dest: empty" ^
  -H "Sec-Fetch-Mode: cors" ^
  -H "Sec-Fetch-Site: cross-site" ^
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" ^
  -H ^"sec-ch-ua: ^\^"Not)A;Brand^\^";v=^\^"99^\^", ^\^"Google Chrome^\^";v=^\^"127^\^", ^\^"Chromium^\^";v=^\^"127^\^"^" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^"

**Comment by JSDID** [comment]
соответственно POST reportinfo тоже не работает, так как нет данных, которые мы получаем
curl "https://app.admss.com/api/v1/reports/aa8f3fd4-f753-4306-a211-46c043bf5b9c/reportinfo" ^
  -H "Accept: application/json, text/plain, */*" ^
  -H "Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6" ^
  -H "Authorization: Bearer 7cca8947-fff2-4c91-a483-370a548881f2" ^
  -H "Connection: keep-alive" ^
  -H "Content-Type: application/json" ^
  -H "Origin: http://localhost:3003" ^
  -H "Referer: http://localhost:3003/" ^
  -H "Sec-Fetch-Dest: empty" ^
  -H "Sec-Fetch-Mode: cors" ^
  -H "Sec-Fetch-Site: cross-site" ^
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36" ^
  -H ^"sec-ch-ua: ^\^"Not)A;Brand^\^";v=^\^"99^\^", ^\^"Google Chrome^\^";v=^\^"127^\^", ^\^"Chromium^\^";v=^\^"127^\^"^" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^" ^
  --data-raw ^"^{^\^"ShowAverages^\^":1^}^"

**Review by kamabzalov — COMMENTED** [review]
@JSDID ждем ответа от бэка

**Comment by JSDID** [comment]
Колонки подвязать?

**Comment by kamabzalov** [comment]
> Колонки подвязать?

то есть?

**Comment by JSDID** [comment]
POST 
curl 'https://app.admss.com/api/v1/reports/3b15c6fb-5c9e-4f3b-84be-371b2ea0b90f/report' \
  -H 'Accept: application/pdf' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer 1b6bf191-c2b5-48b9-9b59-86d68d8d4009' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"'

**Comment by JSDID** [comment]
GET curl
curl 'https://app.admss.com/api/v1/reports/33e88d0e-fa44-4e1d-a279-e8a72f9bbbbb/report' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer 1b6bf191-c2b5-48b9-9b59-86d68d8d4009' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --data-raw '{"itemUID":"1bf644bd-767a-4d1e-a74b-cbad5079fe4d","columns":[{"name":"Buyer Name","data":"Buyer Name","with":0},{"name":"Stock#","data":"Stock#","with":0},{"name":"VIN","data":"VIN","with":0}]}'

**Comment by JSDID** [comment]
POST
curl 'https://app.admss.com/api/v1/reports/3b15c6fb-5c9e-4f3b-84be-371b2ea0b90f/report'
-H 'Accept: application/pdf'
-H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6'
-H 'Authorization: Bearer 1b6bf191-c2b5-48b9-9b59-86d68d8d4009'
-H 'Connection: keep-alive'
-H 'Origin: http://localhost:3003/'
-H 'Referer: http://localhost:3003/'
-H 'Sec-Fetch-Dest: empty'
-H 'Sec-Fetch-Mode: cors'
-H 'Sec-Fetch-Site: cross-site'
-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'
-H 'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"'
-H 'sec-ch-ua-mobile: ?0'
-H 'sec-ch-ua-platform: "Windows"'

**Comment by JSDID** [comment]
Добавил поле columns (взятое со swagger) - как не работало так и сейчас не работает. При получении данных с GET reports/{taskuid}/report все равно ошибка, даже если мы добавили поле columns в POST reports/{useruid}/report

**Comment by JSDID** [comment]
GET 
curl 'https://app.admss.com/api/v1/reports/3b15c6fb-5c9e-4f3b-84be-371b2ea0b90f/report' \
  -H 'Accept: application/pdf' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer 1b6bf191-c2b5-48b9-9b59-86d68d8d4009' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"'

**Comment by JSDID** [comment]
POST curl
curl 'https://app.admss.com/api/v1/reports/33e88d0e-fa44-4e1d-a279-e8a72f9bbbbb/report' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-UA;q=0.8,ru;q=0.7,uk;q=0.6' \
  -H 'Authorization: Bearer 1b6bf191-c2b5-48b9-9b59-86d68d8d4009' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:3003' \
  -H 'Referer: http://localhost:3003/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --data-raw '{"itemUID":"1bf644bd-767a-4d1e-a74b-cbad5079fe4d","columns":[{"name":"Buyer Name","data":"Buyer Name","with":0},{"name":"Stock#","data":"Stock#","with":0},{"name":"VIN","data":"VIN","with":0}]}'

**Review by kamabzalov — APPROVED** [review]

**Pull request merged**
